### ISSUE TITLE
Backend Continuous Integration

### ISSUE THREAD

**Issue by Graeham13** [Capstone-Group/Backend#1]
Circli CI setup needs to be completed

**Comment by LukeBaal** [comment]
Currently the build fails on called setup.py for google-cloud-storage.

Seems like it has something to do with parsing the credentials.json, which is being saved to said file from an environment variable.

**Comment by LukeBaal** [comment]
CircleCI job is passing now. Need to implement handling of code coverage though. Probably need to make a script that reads the coverage report and passes/fails conditionally.

**Comment by LukeBaal** [comment]
Code coverage is now being handled
